name = "wegotbetterdata-comv1"
main = "./src/worker.js"
compatibility_date = "2026-06-01"

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true
not_found_handling = "404-page"

[vars]
SITE_URL = "https://wegotbetterdata.com"
